### ISSUE TITLE
Can you add a LICENSE?

### ISSUE THREAD

**Issue by apolopena** [tlatsas/bash-spinner#6]
Hi,
I love your spinner!
The laws have changed since you first put out this software.  It is my understanding that modification, distribution, etc. is not allowed unless expressly mentioned by the author using a license.
Can you please add a simple license (i.e. MIT, APACHE, BSD-2) to this project?
Thanks,
~Apolo

**Comment by tlatsas** [comment]
Hello @apolopena, thank you for bringing this to my attention. 🙇

**Comment by apolopena** [comment]
My pleasure. Thanks for your great code. 🙏
